### ISSUE TITLE
Drupal security release

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/site_verification#1]
We should issue a new release for the Backdrop version as well:
https://www.drupal.org/project/site_verify/releases/7.x-1.2

**Comment by deekayen** [comment]
Site verification isn't a fork of site_verify - I wrote it from scratch. It doesn't support the upload features that were patched in the Drupal version today.

**Comment by jenlampton** [comment]
Thank you for responding so quickly :)
