### ISSUE TITLE
Error installing Site verification. Cannot extract temporary://update-cache-05e87631/1.x-1.0.1, not a valid archive.

### ISSUE THREAD

**Issue by kreynen** [backdrop-contrib/site_verification#2]
I'm relatively new to Backdrop, but my team at CU maintains https://www.drupal.org/project/site_verify.  I'm able to install other modules on a Pantheon instance, but I keep getting this error when trying to install site_verification.  

If I go to https://backdropcms.org/project/site_verification, I can download and extact https://github.com/backdrop-contrib/site_verification/releases/download/1.x-1.0.1/site_verification.zip

I started a 2nd Pantheon site from scratch and got the same error.  One thing I noticed is Last Updated: Wednesday, July 11, 2018 - 11:40pm in the list details, but when I start the install the date is Site verification 1.x-1.0.1 - Aug 7, 2016

![screen shot 2018-07-12 at 12 09 18 pm](https://user-images.githubusercontent.com/385234/42651399-808469be-85cc-11e8-8a89-805453912830.png)

![screen shot 2018-07-12 at 12 10 16 pm](https://user-images.githubusercontent.com/385234/42651428-a14b400a-85cc-11e8-99ff-c556c9066f6e.png)

Not really sure if this is an issue with this project's repo or a Backdrop.org issue or what the next step to troubleshoot would be.

**Comment by alexfinnarn** [comment]
I can reproduce this issue but only with the current release. The `1.0.0` release did not have that error for me.

Maybe add the one additional commit and tag a `1.0.2` release?

**Comment by alexfinnarn** [comment]
https://github.com/backdrop/backdrop/blob/1.x/core/modules/installer/installer.manager.inc#L987

I'll try to get some debugging info on `$archiver` between the two releases.

**Comment by alexfinnarn** [comment]
So for the first 1.0.0 release, the `$file` is `temporary://update-cache-38df50e0/site_verification.zip` and for the current 1.0.1 release it is `temporary://update-cache-38df50e0/1.x-1.0.1`.

I also checked the "site_map" module (was searching for "Site" in the project browser) and got `temporary://update-cache-38df50e0/site_map.zip` for the `$file`...so I think it is release specific somehow.

**Comment by alexfinnarn** [comment]
@deekayen since you were the last maintainer, do you mind making another release with that new commit in it? I could also do that too.

**Comment by alexfinnarn** [comment]
I tagged a new release to see if it was just a random packaging error. Need to wait for it to show up via the project browser to test.

**Comment by alexfinnarn** [comment]
I was able to install the new release via the Project Browser.

**Comment by alexfinnarn** [comment]
tested and resolved
